spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp
  datasource:
    url: ${POST_URL}
    username: postgres
    password: ${POST_PW}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true                                # ?? ???
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100 # N+1 ??
server:
  port: 8085


